n=int(input())
for i in range(n):
    k=input()
    l=len(k)
    i=0
    b=""
    while(i<l):
        if(k[i]=='0'):
            b=b+"0000"
        if(k[i]=='1'):
            b=b+"0001"
        if(k[i]=='2'):
            b=b+"0010"
        if(k[i]=='3'):
            b=b+"0011"
        if(k[i]=='4'):
            b=b+"0100"
        if(k[i]=='5'):
            b=b+"0101"
        if(k[i]=='6'):
            b=b+"0110"
        if(k[i]=='7'):
            b=b+"0111"
        if(k[i]=='8'):
            b=b+"1000"
        if(k[i]=='9'):
            b=b+"1001"
        if(k[i]=='A'):
            b=b+"1010"
        if(k[i]=='B'):
            b=b+"1011"
        if(k[i]=='C'):
            b=b+"1100"
        if(k[i]=='D'):
            b=b+"1101"
        if(k[i]=='E'):
            b=b+"1110"
        if(k[i]=='F'):
            b=b+"1111"
        i=i+1
    print(b)